### ISSUE TITLE
[Feat] : 엔티티 작성 및 기초 CRUD 설계

### ISSUE THREAD

**Issue by MinchoGreenT** [Mojacknong/Farmus-msa-farm#1]
## ✏️ Description

팜서비스 ERD를 바탕으로 엔티티 클래스를 작성하고, 이에 필요한 주변 클래스를 생성합니다.
API에 필요한 기능 및 서비스가 아닌 기초적인 조회, 생성 서비스만 작성합니다.

세부 도메인으로 crop과 challenge를 나눕니다.
crop엔 작물과 성장일기 및 루틴, challenge엔 유저 챌린지 정보와 미션 인증 게시글이 포함됩니다.

## To-Do List

- [x] 서비스 로직 에러처리
- [x] 전역 에러처리
- [x] challenge 엔티티 작성
- [x] crop 엔티티 작성
- [x] 기본 crud 서비스 로직 작성

## ETC

각 기본 기능을 테스트하고, 로컬 게이트웨이와 연동하여 토큰 필터까지 테스트 후 dev에 머지합니다.
